/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    accommodations: Accommodation;
    'instagram-posts': InstagramPost;
    'manual-blocks': ManualBlock;
    inquiries: Inquiry;
    'calendar-health': CalendarHealth;
    'slug-redirects': SlugRedirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    accommodations: AccommodationsSelect<false> | AccommodationsSelect<true>;
    'instagram-posts': InstagramPostsSelect<false> | InstagramPostsSelect<true>;
    'manual-blocks': ManualBlocksSelect<false> | ManualBlocksSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'calendar-health': CalendarHealthSelect<false> | CalendarHealthSelect<true>;
    'slug-redirects': SlugRedirectsSelect<false> | SlugRedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'instagram-sync-status': InstagramSyncStatus;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'instagram-sync-status': InstagramSyncStatusSelect<false> | InstagramSyncStatusSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  /**
   * Decorative images may have an empty alt text. Existing alt text remains saved.
   */
  decorative?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    ai?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  internalName: string;
  slug: string;
  title: string;
  seo: {
    metaTitle: string;
    metaDescription: string;
    image?: (number | null) | Media;
  };
  layout: (
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        image?: (number | null) | Media;
        actions?:
          | {
              link: {
                label: string;
                kind: 'internal' | 'url' | 'email' | 'phone' | 'anchor';
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'accommodations';
                      value: number | Accommodation;
                    } | null);
                url?: string | null;
                email?: string | null;
                phone?: string | null;
                anchor?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        headline?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        action: {
          label: string;
          kind: 'internal' | 'url' | 'email' | 'phone' | 'anchor';
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'accommodations';
                value: number | Accommodation;
              } | null);
          url?: string | null;
          email?: string | null;
          phone?: string | null;
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        imageSide?: ('right' | 'left') | null;
        action?: {
          label?: string | null;
          kind?: ('internal' | 'url' | 'email' | 'phone' | 'anchor') | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'accommodations';
                value: number | Accommodation;
              } | null);
          url?: string | null;
          email?: string | null;
          phone?: string | null;
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        items: {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'accommodationOverview';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'instagramFeed';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        intro?: string | null;
        mode: 'both' | 'stay' | 'seminar';
        accommodation?: (number | null) | Accommodation;
        id?: string | null;
        blockName?: string | null;
        blockType: 'inquiry';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations".
 */
export interface Accommodation {
  id: number;
  slug: string;
  name: string;
  teaser: string;
  description?: string | null;
  sleeps: number;
  bedSetup?: string | null;
  sizeSqm?: number | null;
  seminarCapable?: boolean | null;
  seminarCapacity?: number | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  floorplan?: (number | null) | Media;
  /**
   * These private links stay on the server and are not exposed by the public API.
   */
  ical?: {
    airbnb?: string | null;
    booking?: string | null;
  };
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts".
 */
export interface InstagramPost {
  id: number;
  externalId: string;
  sourceProfile?: string | null;
  permalink: string;
  caption?: string | null;
  image?: (number | null) | Media;
  publishedAt?: string | null;
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blocks dates on the website and in the private calendar export. Platforms import calendars with a delay.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual-blocks".
 */
export interface ManualBlock {
  id: number;
  accommodation: number | Accommodation;
  /**
   * First blocked day
   */
  startDate: string;
  /**
   * First free day (exclusive)
   */
  endDate: string;
  reason: string;
  inquiry?: (number | null) | Inquiry;
  usage?: ('manual' | 'stay' | 'seminar') | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  kind: 'stay' | 'seminar';
  accommodations: (number | Accommodation)[];
  arrival: string;
  departure?: string | null;
  name: string;
  email: string;
  phone?: string | null;
  guests?: number | null;
  message?: string | null;
  /**
   * Use only after a manual check when a calendar is missing or unavailable.
   */
  confirmDespiteUnknown?: boolean | null;
  status: 'new' | 'reviewing' | 'offered' | 'confirmed' | 'cancelled' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-health".
 */
export interface CalendarHealth {
  id: number;
  key: string;
  accommodation: number | Accommodation;
  provider: 'airbnb' | 'booking';
  consecutiveFailures: number;
  lastSuccessAt?: string | null;
  lastFailureAt?: string | null;
  alertedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slug-redirects".
 */
export interface SlugRedirect {
  id: number;
  fromPath: string;
  targetCollection: 'pages' | 'accommodations';
  targetId: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'accommodations';
        value: number | Accommodation;
      } | null)
    | ({
        relationTo: 'instagram-posts';
        value: number | InstagramPost;
      } | null)
    | ({
        relationTo: 'manual-blocks';
        value: number | ManualBlock;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'calendar-health';
        value: number | CalendarHealth;
      } | null)
    | ({
        relationTo: 'slug-redirects';
        value: number | SlugRedirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  decorative?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        ai?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  internalName?: T;
  slug?: T;
  title?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        image?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              image?: T;
              actions?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          kind?: T;
                          reference?: T;
                          url?: T;
                          email?: T;
                          phone?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              headline?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              action?:
                | T
                | {
                    label?: T;
                    kind?: T;
                    reference?: T;
                    url?: T;
                    email?: T;
                    phone?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              action?:
                | T
                | {
                    label?: T;
                    kind?: T;
                    reference?: T;
                    url?: T;
                    email?: T;
                    phone?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accommodationOverview?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        instagramFeed?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        inquiry?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              mode?: T;
              accommodation?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations_select".
 */
export interface AccommodationsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  teaser?: T;
  description?: T;
  sleeps?: T;
  bedSetup?: T;
  sizeSqm?: T;
  seminarCapable?: T;
  seminarCapacity?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  floorplan?: T;
  ical?:
    | T
    | {
        airbnb?: T;
        booking?: T;
      };
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts_select".
 */
export interface InstagramPostsSelect<T extends boolean = true> {
  externalId?: T;
  sourceProfile?: T;
  permalink?: T;
  caption?: T;
  image?: T;
  publishedAt?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual-blocks_select".
 */
export interface ManualBlocksSelect<T extends boolean = true> {
  accommodation?: T;
  startDate?: T;
  endDate?: T;
  reason?: T;
  inquiry?: T;
  usage?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  kind?: T;
  accommodations?: T;
  arrival?: T;
  departure?: T;
  name?: T;
  email?: T;
  phone?: T;
  guests?: T;
  message?: T;
  confirmDespiteUnknown?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-health_select".
 */
export interface CalendarHealthSelect<T extends boolean = true> {
  key?: T;
  accommodation?: T;
  provider?: T;
  consecutiveFailures?: T;
  lastSuccessAt?: T;
  lastFailureAt?: T;
  alertedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slug-redirects_select".
 */
export interface SlugRedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  targetCollection?: T;
  targetId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  navigation?:
    | {
        link: {
          label: string;
          kind: 'internal' | 'url' | 'email' | 'phone' | 'anchor';
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'accommodations';
                value: number | Accommodation;
              } | null);
          url?: string | null;
          email?: string | null;
          phone?: string | null;
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  footer?: {
    /**
     * Leave empty to use the website name.
     */
    title?: string | null;
    description?: string | null;
    apartmentsHeading?: string | null;
    linksHeading?: string | null;
    links?:
      | {
          link: {
            label: string;
            kind: 'internal' | 'url' | 'email' | 'phone' | 'anchor';
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'accommodations';
                  value: number | Accommodation;
                } | null);
            url?: string | null;
            email?: string | null;
            phone?: string | null;
            anchor?: string | null;
            newTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    contactHeading?: string | null;
    /**
     * The current year and © are added automatically.
     */
    copyrightText?: string | null;
  };
  operatorName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  streetAddress?: string | null;
  postalCode?: string | null;
  city?: string | null;
  country?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-sync-status".
 */
export interface InstagramSyncStatus {
  id: number;
  snapshotId?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  profileUrl?: string | null;
  lastError?: string | null;
  lastImportedCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  navigation?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              kind?: T;
              reference?: T;
              url?: T;
              email?: T;
              phone?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        title?: T;
        description?: T;
        apartmentsHeading?: T;
        linksHeading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    kind?: T;
                    reference?: T;
                    url?: T;
                    email?: T;
                    phone?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        contactHeading?: T;
        copyrightText?: T;
      };
  operatorName?: T;
  contactEmail?: T;
  contactPhone?: T;
  streetAddress?: T;
  postalCode?: T;
  city?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-sync-status_select".
 */
export interface InstagramSyncStatusSelect<T extends boolean = true> {
  snapshotId?: T;
  startedAt?: T;
  completedAt?: T;
  profileUrl?: T;
  lastError?: T;
  lastImportedCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}